id: I1CB90919
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-28T05:46:25+00:00'
last_modified: '2022-06-14T08:19:40.512645+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13817
  title: བརྡ་དག་སྙན་ངག་སོགས་ཐ་སྙད་རིག་གནས་ཀྱི་གཞུང་གཅེས་བཏུས།
  author: ''
  base:
    EA83:
      image_group_id: I1KG15834
      title: ''
      total_pages: ''
      order: 1
      base_file: EA83.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
