id: P5839F145
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13817
  title: བརྡ་དག་སྙན་ངག་སོགས་ཐ་སྙད་རིག་གནས་ཀྱི་གཞུང་གཅེས་བཏུས།
  volumes:
    a1b36d6e8fb54facaf9636bff5461b20:
      image_group_id: I1KG15834
      title: ''
      base_file: v001.txt
  author: ''
